# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_4HsUNQEAvXVr_jtu0mZ1476kXXNUs4n
"""

name = input("Введите имя")
print("Привет," + name)